version: '3'
services:
  admin:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - TARGETPLATFORM=linux/amd64
    container_name: sitebuilder_app
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      DB_HOST: sitebuilder_db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes: 
      - ./:/var/www/html
      - ./.docker/certs/:/etc/letsencrypt
      - ./.docker/sites-avaliable/:/etc/apache2/sites-available
    networks:
    - app-network
    ports:
      - 8004:8000
      - 443:443
    depends_on:
      sitebuilder_db:
        condition: service_healthy
    restart: unless-stopped
  
  sitebuilder_db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
        - ./.docker/mysql/dbdata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "33071:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${DB_USERNAME} -p${DB_PASSWORD}"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  app-network:
    driver: bridge