import SlideinBannerEventComponent from './SlideinBannerEventComponent/initComponent.js';
import HtmlBlockEventDescriptionComponent from './HtmlBlockEventDescriptionComponent/initComponent.js';
import ListBenchMapGalleryEventComponent from './ListBenchMapGalleryEventComponent/initComponent.js';
import HtmlBlockEventAttachmentsComponent from './HtmlBlockEventAttachmentsComponent/initComponent.js';
import BlockEventGoogleMapsLocationComponent from './BlockEventGoogleMapsLocationComponent/initComponent.js';
import EventPublishersBlockComponent from './EventPublishersBlockComponent/initComponent.js';
import EventPublisherBlockComponent from './EventPublisherBlockComponent/initComponent.js';

window.SlideinBannerEventComponent = SlideinBannerEventComponent;
window.HtmlBlockEventDescriptionComponent = HtmlBlockEventDescriptionComponent;
window.ListBenchMapGalleryEventComponent = ListBenchMapGalleryEventComponent;
window.HtmlBlockEventAttachmentsComponent = HtmlBlockEventAttachmentsComponent;
window.BlockEventGoogleMapsLocationComponent = BlockEventGoogleMapsLocationComponent;
window.EventPublishersBlockComponent = EventPublishersBlockComponent;
window.EventPublisherBlockComponent = EventPublisherBlockComponent;