import SlideinBannerEventComponent from './SlideinBannerEventComponent/initComponent.js';
import HtmlBlockEventDescriptionComponent from './HtmlBlockEventDescriptionComponent/initComponent.js';
import ListBenchMapGalleryEventComponent from './ListBenchMapGalleryEventComponent/initComponent.js';
import HtmlBlockEventAttachmentsComponent from './HtmlBlockEventAttachmentsComponent/initComponent.js';
import BlockEventGoogleMapsLocationComponent from './BlockEventGoogleMapsLocationComponent/initComponent.js';
import BlockEventPublishersComponent from './BlockEventPublishersComponent/initComponent.js';
import BlockEventPublisherComponent from './BlockEventPublisherComponent/initComponent.js';

window.SlideinBannerEventComponent = SlideinBannerEventComponent;
window.HtmlBlockEventDescriptionComponent = HtmlBlockEventDescriptionComponent;
window.ListBenchMapGalleryEventComponent = ListBenchMapGalleryEventComponent;
window.HtmlBlockEventAttachmentsComponent = HtmlBlockEventAttachmentsComponent;
window.BlockEventGoogleMapsLocationComponent = BlockEventGoogleMapsLocationComponent;
window.BlockEventPublishersComponent = BlockEventPublishersComponent;
window.BlockEventPublisherComponent = BlockEventPublisherComponent;